{% set name = "ua-parser-builtins" %}
{% set version = "0.18.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/py3/u/ua_parser_builtins/ua_parser_builtins-{{ version }}-py3-none-any.whl
  sha256: 51cbc3d6ab9c533fc12fc7cededbef503c8d04e465d0aff20d869e15320b5ca9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed ua_parser_builtins-{{ version }}-py3-none-any.whl

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    # circular dependency
    # - ua-parser

test:
  imports:
    - ua_parser_builtins
  # circular dependency
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ua-parser/uap-python/tree/master/ua-parser-builtins
  summary: Precompiled ruleset for ua-parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
